# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MWTabViewExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'MWTabView', :path => '../'

  # Pods for MWTabViewExample

end

target 'MWTabViewExampleObjC' do
  
  use_frameworks!
  
  pod 'MWTabView', :path => '../'
  
end
